# Auto-generated by Wutong ASI
# Import necessary libraries for the Python code quality analysis
import flake8.api.legacy as fala
from pylint import epylint as lint

def analyze_python_code(code):
    """
    Analyzes Python code using AI-powered tools to check for errors and style issues.
    
    Args:
    - code (str): A string containing the Python source code to be analyzed.

    Returns:
    - dict: A dictionary containing the results of the analysis, including error messages and style scores.
    """
    # Use Flake8 to find syntax errors and coding style problems
    flake_results = fala.run_code(code)
    flake_errors = [error for error in flake_results[0]]

    # Use pylint to get a score on code quality
    lint_stdout, _ = lint.py_run(f"-c '{code}'", return_std=True)
    pylint_score = float(lint_stdout.getvalue().split('Your code has been rated at ')[1].split('/')[0])

    analysis_result = {
        "flake_errors": flake_errors,
        "pylint_score": pylint_score
    }

    return analysis_result

# Example Python code snippet to analyze
sample_code = """
def hello_world():
    print("Hello, world!")

hello_world()
"""

# Analyze the sample code and print the results
analysis = analyze_python_code(sample_code)
print("Flake8 Errors:", analysis["flake_errors"])
print("Pylint Score:", analysis["pylint_score"])