# Auto-generated by Wutong ASI
# Import necessary libraries
import flake8.api.legacy as fala

def analyze_python_code(file_path):
    """
    Analyzes the Python code in the given file for potential issues using flake8.
    
    Args:
        file_path (str): The path to the Python file to be analyzed.
        
    Returns:
        list: A list of tuples, each containing a line number and a message describing an issue.
    """
    # Use flake8 to analyze the code
    style_guide = fala.get_style_guide()
    report = style_guide.check_files([file_path])
    
    # Extract issues from the report
    issues = []
    for error in report.get_statistics():
        if error.code != 'E902':  # Ignore E902 errors (indicates an unparseable file)
            issues.append((error.line_number, f"{error.error_code}: {error.text}"))
    
    return issues

# Example usage
if __name__ == "__main__":
    file_path = 'example.py'  # Specify the path to your Python file
    issues = analyze_python_code(file_path)
    
    # Print any found issues
    if issues:
        print("Issues found in the code:")
        for line, message in issues:
            print(f"Line {line}: {message}")
    else:
        print("No issues found.")