# Auto-generated by Wutong ASI
# Import necessary libraries for the AI-powered Python code quality analyzer
import ast
from pylint import epylint as lint

def analyze_code_quality(file_path):
    """
    Function to analyze the quality of Python code using AI and Linting tools.
    
    :param file_path: str, path to the Python source code file
    """
    # Use abstract syntax tree (AST) to parse the code for structural analysis
    with open(file_path, 'r') as source_code:
        tree = ast.parse(source_code.read())
    
    # Perform linting using pylint's epylint interface
    rcfile = None  # Using default config
    linter = lint.lint.Run([file_path], rcfile=rcfile)
    
    # Extract results from the linting process
    global_stats, _ = linter.lint_all()
    
    # Print quality metrics based on pylint scores
    print(f"Code Quality Score: {global_stats.global_note:.2f}")
    print("Code Issues Detected:")
    for issue in global_stats.by_module.values():
        for message in issue:
            print(message.msg)

# Example usage of the function with a sample Python file path
analyze_code_quality('example.py')