# Auto-generated by Wutong ASI
# Importing necessary libraries
import flake8.api.legacy as f8api

def analyze_python_code(file_path):
    """
    Analyzes the quality of Python code using Flake8.
    
    Parameters:
    - file_path: str, path to the Python file to be analyzed.
    
    Returns:
    - report: dict, containing statistics about the code quality.
    """
    # Running Flake8 on the provided file
    style_guide = f8api.get_style_guide()
    report = style_guide.check_files([file_path])
    
    return report

# Example usage of the function
if __name__ == "__main__":
    file_to_analyze = "example.py"  # Path to the Python script you want to analyze
    analysis_result = analyze_python_code(file_to_analyze)
    
    print("Total errors:", analysis_result.total_errors)  # Prints total number of errors in the code
    for error in analysis_result.get_statistics():
        print(f"{error.count} {error.code} - {error.msg}")  # Detailed statistics for each type of error
    
    if analysis_result.total_errors == 0:
        print("No errors found! Your code is clean.")
    else:
        print("Please fix the errors to improve your code quality.")

# This script uses Flake8, an open-source Python tool that checks Python source code for style and programming errors.