# Auto-generated by Wutong ASI
# Importing necessary libraries
import ast
from pylint import epylint as lint

def analyze_python_code(code):
    """
    Analyzes Python code for potential issues using Pylint.
    
    Args:
    - code (str): The Python source code to be analyzed.
    
    Returns:
    - float: The score given by Pylint, where higher is better.
    """
    # Writing the code into a temporary file
    with open('temp_code.py', 'w') as f:
        f.write(code)
    
    # Running pylint on the temporary file
    (linter_stdout, linter_stderr) = lint.run(['--output-format=parseable', 'temp_code.py'])
    
    # Parsing pylint output to extract score
    for line in linter_stdout.split('\n'):
        if line.startswith('Your code has been rated at'):
            score_str = line.split()[4].replace(',', '')
            return float(score_str)
    
    return None

# Example usage
code_to_analyze = """
def add(a, b):
    return a + b
"""
score = analyze_python_code(code_to_analyze)
print(f"Code quality score: {score:.2f}")