# Auto-generated by Wutong ASI
# Import necessary libraries
from pylint import epylint as lint

def analyze_code(file_path):
    """
    Function to analyze the quality of Python code using Pylint.
    
    Args:
        file_path (str): The path to the Python file to be analyzed.

    Returns:
        dict: A dictionary containing the analysis results.
    """

    # Define options for pylint
    options = ('--output-format=json', file_path)

    # Run pylint and capture the output
    lint_output, _ = lint.lint_run(options)

    # Parse the JSON output to get a dictionary of results
    analysis_results = json.loads(lint_output.read())

    return analysis_results

# Example usage
if __name__ == "__main__":
    file_to_analyze = "example.py"
    code_quality = analyze_code(file_to_analyze)
    
    # Print results
    print("Code Quality Analysis:")
    for issue in code_quality['messages']:
        print(f"Line {issue['line']}: {issue['type']} - {issue['message']}")