# Auto-generated by Wutong ASI
# Import necessary libraries
import ast
from pygount import SourceAnalysis

def analyze_code_quality(code):
    """
    Analyze the quality of the provided Python code using PyGount.
    
    Args:
    - code (str): The source code to analyze.

    Returns:
    - dict: A dictionary containing analysis results.
    """
    # Create a temporary file for storing the code
    with open("temp.py", "w") as f:
        f.write(code)

    # Analyze the Python code using PyGount
    result = SourceAnalysis.from_file("temp.py")

    # Clean up by removing the temporary file
    import os
    os.remove("temp.py")
    
    return result.as_dict()

# Example usage of the function with a simple Python code snippet
code_snippet = """
def add_numbers(a, b):
    return a + b

result = add_numbers(5, 3)
print(result)
"""

# Analyze the quality of the code snippet
quality_analysis = analyze_code_quality(code_snippet)

# Print the analysis results
print("Code Quality Analysis:")
for key, value in quality_analysis.items():
    print(f"{key}: {value}")