# Auto-generated by Wutong ASI
# Importing required libraries
import ast
from pyflakes import checker

def analyze_python_code(code):
    """
    Analyzes the provided Python code for potential errors and bad practices.
    
    Args:
    - code (str): The Python code as a string.

    Returns:
    - list: A list of error messages found in the code.
    """
    # Parsing the Python code into an AST
    parsed_code = ast.parse(code)
    
    # Creating a checker object to analyze the AST
    check_obj = checker.Checker(parsed_code, filename="<string>")
    
    # Running checks and collecting errors
    errors = []
    for error in check_obj.messages:
        errors.append(error.message % error.args)

    return errors

# Example Python code to be analyzed
example_code = """
def add(a, b):
    c = a + b
    return c
"""

# Analyzing the example code
issues = analyze_python_code(example_code)
if issues:
    print("Code issues found:")
    for issue in issues:
        print(f"- {issue}")
else:
    print("No issues found. Code is clean.")