# Auto-generated by Wutong ASI
# Import necessary libraries
import ast
from pylint import epylint as lint

def analyze_python_code(file_path):
    """
    Analyzes the Python code in the given file for potential issues.

    Args:
    - file_path (str): The path to the Python file to be analyzed.

    Returns:
    - None: Prints the analysis results.
    """

    # Use pylint to analyze the code
    linter = lint.Run([file_path], exit=False)
    score, report = linter.lint_all()

    # Print the results of the analysis
    print(f"Code quality score: {score}")
    print("Report:")
    print(report)

# Example usage
analyze_python_code('example.py')